export const experienceCategories = [
    "Wellness",
    "Culinary",
    "Adventure",
    "Creative",
    "Social",
];

export const experiences = [
    {
        id: "1",
        title: "Sunset Yoga Flow",
        category: "Wellness",
        type: "Live",
        hostId: "h1",
        duration: "60 min",
        description: "Unwind with a gentle flow yoga session as the sun sets over the marina waters. Suitable for all levels.",
        price: "$25",
        rating: 4.9,
        reviews: 124,
        nextSession: "Tomorrow, 6:00 PM",
        skillLevel: "Beginner",
        location: "Moore Haven Marina - Deck 2",
        image: "/images/exp-yoga.png",
        // Yoga With Adriene - Sunset Yoga (Works)
        videoId: "v7AYKMP6rOE",
    },
    {
        id: "2",
        title: "Coastal Cooking Class",
        category: "Cooking",
        type: "Live",
        hostId: "h2",
        duration: "2 hours",
        description: "Learn to prepare a 3-course meal using fresh, local ingredients sourced from nearby farms.",
        price: "$85",
        rating: 5.0,
        reviews: 89,
        nextSession: "Sat, 11:00 AM",
        skillLevel: "Intermediate",
        location: "Culinary Studio",
        image: "/images/exp-cooking.png",
        // User provided cooking video
        videoId: "N9t7auky2c0",
    },
    {
        id: "3",
        title: "Eco-Kayak Tour",
        category: "Adventure",
        type: "Live",
        hostId: "h3",
        duration: "3 hours",
        description: "Explore the unique ecosystem of the Everglades with a guided kayak tour. Spot wildlife and learn about conservation.",
        price: "$60",
        rating: 4.8,
        reviews: 215,
        nextSession: "Sun, 8:00 AM",
        skillLevel: "All Levels",
        location: "Marina Dock",
        image: "/images/hero-home.jpg",
        // User provided kayak video
        videoId: "cNLfRgAsqeo",
    },
    {
        id: "4",
        title: "Pottery & Wine",
        category: "Arts",
        type: "Live",
        hostId: "h4",
        duration: "2 hours",
        description: "Get your hands dirty and create your own ceramic bowl or vase on the wheel.",
        price: "$55",
        rating: 4.7,
        reviews: 56,
        nextSession: "Fri, 4:00 PM",
        skillLevel: "Beginner",
        location: "Art Studio",
        image: "/images/exp-pottery.png",
        // User provided pottery video
        videoId: "ClgwJbwyIoo",
    },
    {
        id: "5",
        title: "Morning Meditation",
        category: "Wellness",
        type: "On-demand",
        hostId: "h1",
        duration: "15 min",
        description: "A guided audio meditation to help you center yourself and find calm anywhere.",
        price: "Free",
        rating: 4.9,
        reviews: 342,
        nextSession: null,
        skillLevel: "Beginner",
        location: "Virtual",
        image: "/images/hero-home.jpg",
        // Goodful - 10 Min Morning Meditation (Works)
        videoId: "ENYYb5vIMkU",
    },
    {
        id: "6",
        title: "Community Potluck",
        category: "Culture",
        type: "Live",
        hostId: "h5",
        duration: "3 hours",
        description: "Join neighbors and friends for a communal meal under the stars. Bring a dish or just yourself.",
        price: "Donation",
        rating: 5.0,
        reviews: 45,
        nextSession: "Thu, 7:00 PM",
        skillLevel: "All Levels",
        location: "Village Green",
        image: "/images/exp-dining.png",
        // Reverted to static placeholder image per user request
        videoId: undefined,
    },
];
